### ISSUE TITLE
Deleting line-item needs advertiser_id in the url path.

### ISSUE THREAD

**Issue by nelsonsequiera** [numberly/appnexus-client#16]
I have raised a PR for the same. Please consider. Also thanks for this whole repo. saved days of my work

**Comment by ramnes** [comment]
You're welcome! We're glad that our small contribution to the open-source world is actually useful to some. 👍

**Comment by AliAsgharDeo** [comment]
I have a similar requirement where i need to download report "advertiser_analytics" which requires an advertiser id. Any help on how i can download the report? Any sample would be helpful. "network_analytics" report is downloading correctly
