### ISSUE TITLE
AdServer service generates wrong api path

### ISSUE THREAD

**Issue by yartseva** [numberly/appnexus-client#34]
Hello,
I try to use the appnexus-client to get the sellers list from AppNexus:

ad-server
https://api.appnexus.com/ad-server?start_element=0&num_elements=1 {'Authorization': 'authn:222059:86183906c3fb3:ams1'} None
b'{"error":"Invalid path given"}'

However, it works with the following path:
https://api.appnexus.com/adserver

Is it possible to correct the service path in the package? 
I'm quite new to the api / packages development, otherwise would do. 
If you have the patience to teach me things, could contribute in the future. 

Kind regards,
Anastasia

**Comment by ramnes** [comment]
The last commit on `master` should fix this, can you confirm? You will have to import `Adserver` rather than `AdServer`.

**Comment by ramnes** [comment]
I'll go ahead and close this, feel free to ping me if this is still an issue!
