### ISSUE TITLE
Passing advertiser id to Report object

### ISSUE THREAD

**Issue by romanumero** [numberly/appnexus-client#35]
Thanks to your team for developing this library. It's saved me time and works like a charm.

Can parameters be passed to the Report object? The Attribution Conversion report requires advertiser_id and I'm not clear on the best practice to accomplish this.

**Comment by rambobinator** [comment]
Hi, glad to hear that it helps you !

in this way it should work:
`
report = Report(json).save(advertiser_id=42)
`

**Comment by romanumero** [comment]
Awesome. Thanks
