### ISSUE TITLE
Property is_ready always returns false

### ISSUE THREAD

**Issue by moeidur** [numberly/appnexus-client#45]
In `model.py`, the property `is_ready` (line 137) always returns false, regardless of the value of the variable `execution_status`. 

I ran the following code: 
```
json = {
    "report_type": "network_analytics",
    "timezone": "Europe/Amsterdam",
    "columns": COLOUMNS,
    "filters": [{"advertiser_currency": ["NOK"]}],
    "report_interval": "last_30_days",
    "format": "csv"
}
report = Report(json).save()
report.is_ready
```

I got the result False even though the execution status in the response was "ready".

This makes it impossible to check that the report is ready and further makes the function `download` (line 130) retry the total number of times specified in `retry_count` regardless of whether the report is ready earlier or not.

**Comment by rambobinator** [comment]
Hi,
Thanks for submitting this issue, i made a PR that fix it.

**Comment by moeidur** [comment]
> Hi,
> Thanks for submitting this issue, i made a PR that fix it.

Thank you for fixing it so quickly! :)

**Comment by rambobinator** [comment]
Hi,
The fix is now on master and part of our last release 0.8.1
