### ISSUE TITLE
Wrong name: PlateformMember vs PlatformMember

### ISSUE THREAD

**Issue by razyalov** [numberly/appnexus-client#9]
There is a bug in the platform-member definition. Should be platform without 'e'

**Comment by Shir0kamii** [comment]
Hi! Indeed, it seems my french side kicked in, sorry for that.

I just published the fix in the version 0.3.1.

Thank you for your feedback!

**Comment by razyalov** [comment]
Thanks. I don't see it published yet. Does it take some time before it shows up here and on pip?

**Comment by Shir0kamii** [comment]
I published on pip but not github, done now.

**Comment by razyalov** [comment]
THANK! you are awesome for doing it so fast!

**Comment by Shir0kamii** [comment]
You're welcome. :)
